language:
    - php

php:
    - 5.3
#    - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=1
#    - WP_VERSION=master WP_MULTISITE=0
#    - WP_VERSION=3.5.2 WP_MULTISITE=1
#    - WP_VERSION=3.5.2 WP_MULTISITE=0

before_install:
    - sudo apt-get update
    - git submodule update --init --recursive

before_script:
#    - pear config-set auto_discover 1
    - pear install PHP_CodeSniffer
    - pear install phpunit/phpcpd
    - pear channel-discover pear.phpmd.org
#    - pear channel-discover pear.pdepend.org
    - pear install phpmd/PHP_PMD
    - phpenv rehash
    - git clone git://github.com/mrchrisadams/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
#    - export WP_TESTS_DIR=/tmp/wordpress-tests/
#    - bash ci/bin/install-wp-tests.sh wordpress_test root '' ${WP_VERSION} 
    - sudo apt-get install clamav -qq
    - sudo apt-get install clamav-freshclam -qq
    - sudo apt-get install clamav-unofficial-sigs -qq
    - sudo freshclam --quiet

script:
    - find . \( -name '*.php' -o -name '*.inc' \) -exec php -lf {} \;
    - clamscan --algorithmic-detection=yes --detect-pua=yes --detect-structured=yes --exclude='(pasteword|jquery)\.js' --infected --phishing-cloak=yes --phishing-sigs=yes --phishing-ssl=yes --recursive --scan-archive=yes --scan-elf=yes --scan-html=yes --scan-ole2=yes --scan-pdf=yes --scan-pe=yes .
    - phpcs -s -n --standard=ci/phpcs.travis.ruleset.xml .
    - phpcpd .
    - phpmd . --exclude TBD text ci/phpmd.ruleset.xml
#    - phpunit

notifications:
    email:
        on_failure: change
