language:
    - php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.6.0 WP_MULTISITE=1
    - WP_VERSION=3.6.0 WP_MULTISITE=0

before_install:
    - sudo apt-get update
    - git submodule update --init --recursive

before_script:
    - pear config-set auto_discover 1
    - pear install PHP_CodeSniffer
    - pear install phpunit/phpcpd
    - pear channel-discover pear.phpmd.org
    - pear channel-discover pear.pdepend.org
    - pear install phpmd/PHP_PMD
    - phpenv rehash
    - git clone git://github.com/mrchrisadams/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
    - export PHPMD_EXCLUDE="Akismet.class.php,class-redrokk-metabox-class.php,video-quick-edit.php,inc.flickr.php,screen-meta-links.php,EDD_License_Handler.php,EDD_SL_Plugin_Updater.php,jquery.cookie.js,jquery.bxslider.js,jquery.easing.1.3.js,jquery.fitvids.js"
#    - export WP_TESTS_DIR=/tmp/wordpress-tests/
#    - bash tests/bin/install-wp-tests.sh wordpress_test root '' ${WP_VERSION} 

script:
    - find . \( -name '*.php' -o -name '*.inc' \) -exec php -lf {} \;
    - phpcs -s -n --standard=tests/phpcs.ruleset.xml .
    - phpcpd .
    - phpmd . --exclude ${PHPMD_EXCLUDE} text tests/phpmd.ruleset.xml
#    - phpunit

notifications:
    email:
        on_success: change
        on_failure: change
